spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait: 60000
      min-idle: 5
      initial-size: 20
      validation-query: select 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)