spring:
  profiles:
    active: dev

  # http请求编码
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

# mybatis配置
mybatis:
  type-aliases-package: com.org.springboot.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    #当设置为‘true’的时候，懒加载的对象可能被任何懒属性全部加载。否则，每个属性都按需加载
    aggressive-lazy-loading: false
    #全局性设置懒加载。如果设为‘false’，则所有相关联的都会被初始化加载
    lazy-loading-enabled: true
    # 属性为true来开启驼峰功能
    map-underscore-to-camel-case: true